learning_rates: [0.0001]
architectures:
  # layer and the rest is its kwargs
  - []
  - - layer: dense_relu
      units: 512
    - layer: dense_relu
      units: 256
  - - layer: dense_relu
      units: 1024
    - layer: dense_relu
      units: 512
